---
project-name: exchange
pre-deploy: 'bundle exec rake db:migrate'
git-remote: git@github.com:artsy/exchange.git
post-deploy: .circleci/deploy_event.sh
hokusai-required-version: ">=0.5.8"
template-config-files:
  - s3://artsy-citadel/k8s/hokusai-vars.yml
